organization:
  name: "${ORGANISATION_NAME}"

clusters:
  - id: default
    name: My test kafka cluster
    color: "#0013E7"
    ignoreUntrustedCertificate: false
    bootstrapServers: "$KAFKA_BOOTSTRAP_SERVER"

auth:
  demo-users:
    - email: "${ADMIN_EMAIL}"
      password: "${ADMIN_PSW}"
      groups:
        - ADMIN
